# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Skazitron/shahirkazi.com

media_folder: /static/media
public_folder: /media

collections:
  - name: personal-posts
    label: personal-posts
    folder: /content/personal
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Timestamp, name: timestamp, widget: datetime}
      - { label: Body, name: body, widget: richtext }

  - name: shariq-posts
    label: shariq-posts
    folder: /content/shariq
    create: true
    fields: 
      - { label: Title, name: title, widget: string}
      - { label: Timestamp, name: timestamp, widget: datetime}
      - { label: Body, name: body, widget: richtext}